<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Motivos para Perder Peso</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            text-align: center;
            background-color: #f4f4f4;
        }
        header {
            background-color: #007bff;
            color: white;
            padding: 20px;
            font-size: 24px;
        }
        .container {
            max-width: 800px;
            margin: 20px auto;
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        button {
            background-color: #007bff;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
        }
        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <header>Motivos para Perder Peso</header>
    <div class="container">
        <h1>Por que Perder Peso?</h1>
        <p>Entenda os benefícios da perda de peso para a sua saúde e bem-estar.</p>
        <h2>1. Saúde Cardiovascular</h2>
        <p>Reduzir o excesso de peso pode diminuir os riscos de doenças cardíacas e hipertensão.</p>
        <h2>2. Controle da Diabetes</h2>
        <p>Manter um peso saudável ajuda a prevenir e controlar a diabetes tipo 2.</p>
        <h2>3. Melhor Mobilidade</h2>
        <p>Menos peso significa menos pressão sobre as articulações, melhorando a mobilidade e reduzindo dores.</p>
        <h2>4. Bem-estar Mental</h2>
        <p>Ter um estilo de vida saudável pode melhorar sua autoestima e reduzir os níveis de estresse e ansiedade.</p>
        <button onclick="alert('Saiba mais sobre um estilo de vida saudável!')">Saiba Mais</button>
    </div>
</body>
</html>
